/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("jkt.patterns.kotlin-application-conventions")
}

dependencies {
    implementation(project(":functional"))
}

application {
    // Define the main class for the application.
    mainClass.set("jkt.patterns.app.AppKt")
}
